#!/bin/bash

if [[ -f /etc/redhat-release ]] && grep Fedora /etc/redhat-release > /dev/null 2>&1; then
  echo "fedora"
  exit 0
fi

if [[ -f /etc/gentoo-release ]]; then
  echo "gentoo"
  exit 0
fi

if [[ $OSTYPE == "darwin"* ]]; then
  echo "osx"
  exit 0
fi

echo "unknown distro" 1>&2
exit 1
