#!/bin/bash

if ! distro=$(detect-distro); then
    echo "Could not detect distro"
    exit 1
fi

case $distro in
"fedora")
    exec install-if-newer fedora "sudo dnf install"
    ;;
"gentoo")
    exec install-if-newer gentoo "sudo emerge"
    ;;
"osx")
    exec install-if-newer brew "brew install"
    ;;
*)
    echo "Unsupported distro: $distro"
    exit 1
    ;;
esac
