#!/bin/bash
# run a command once only if the state file doesn't exist

[[ -z $ROOT ]] && echo "ROOT: missing" && exit 1
[[ $# != 2 ]] && echo "Usage: $0 <state-file> <command>" && exit 1

state=$1
cmd=$2
marker=$ROOT/state/$state

[[ -f $marker ]] && exit 0
echo "$state: running once"
eval "$cmd" && touch $marker
