#!/usr/bin/env python3
"""
Creates a relative symbolic link.
"""

import sys
import os

if __name__ == "__main__":
    link_name = sys.argv[1]
    source = sys.argv[2]
    print(link_name, '->', source)
    directory = os.path.dirname(link_name)
    source = os.path.relpath(source, directory)
    os.symlink(source, link_name)
