#!/usr/bin/env python3

import argparse
import os
import sys
import stat
import re

sys.path.append(os.path.dirname(__file__))

from lib.lookup import Lookup

def setup_parser():
    parser = argparse.ArgumentParser()
    Lookup.setup_parser(parser)

    sp = parser.add_subparsers()

    render = sp.add_parser('render')
    render.add_argument('source')
    render.add_argument('target')
    render.set_defaults(action=render_action)

    render = sp.add_parser('keys')
    render.add_argument('name')
    render.set_defaults(action=keys_action)

    return parser

def setup_lookup(ns):
    ns.root = os.getenv('ROOT')

    if ns.root is None:
        raise Exception('ROOT: missing environment variable')

    return Lookup.load(ns)

def keys_action(ns):
    lookup = setup_lookup(ns)

    for key in lookup._keys(ns.name):
        print(key)

def render_action(ns):
    lookup = setup_lookup(ns)

    source = ns.source
    target = ns.target
    target_dir = os.path.dirname(os.path.abspath(target))

    if not os.path.isdir(target_dir):
        print('creating directory: {}'.format(target_dir))
        os.makedirs(target_dir)

    print('{} →  {}'.format(source, target))

    with open(source, 'r') as s:
        template = s.read()

        try:
            out = lookup._render(template)
        except Exception as e:
            raise Exception('{}: {}'.format(source, e))

    with open(target, 'w') as t:
        t.write(out)

if __name__ == "__main__":
    parser = setup_parser()
    ns = parser.parse_args()
    ns.action(ns)
