variables:
    MUTT_SIGNATURE: John-John
    PROFILE_NAME: John-John Tedro
    PROFILE_EMAIL: johnjohn.tedro@gmail.com
    USER: udoprog
    GPG_KEY: 3ECA40B9
    PRIMARY_MAIL: personal
    SECONDARY_MAIL: work
    SECONDARY_MAILBOX: w

profiles:
    home:
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell
    remote:
        PROFILE_TMUX_PREFIX: C-b
        PROFILE_ZSH_THEME: afowler
    work:
        PRIMARY_MAIL: work
        SECONDARY_MAIL: personal
        SECONDARY_MAILBOX: p
        USER: udoprog
        PROFILE_NAME: John-John Tedro
        PROFILE_EMAIL: udoprog@spotify.com
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell

secrets:
  - EMAIL
  - SMTP_PASS
  - IMAP_PASS
  - SMTP_URL
  - WORK_EMAIL
  - WORK_SMTP_PASS
  - WORK_IMAP_PASS
  - WORK_SMTP_URL
