profiles:
    home:
        USER: udoprog
        PROFILE_NAME: John-John Tedro
        PROFILE_EMAIL: johnjohn.tedro@gmail.com
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell
    remote:
        USER: udoprog
        PROFILE_NAME: John-John Tedro
        PROFILE_EMAIL: johnjohn.tedro@gmail.com
        PROFILE_TMUX_PREFIX: C-b
        PROFILE_ZSH_THEME: afowler
    work:
        USER: udoprog
        PROFILE_NAME: John-John Tedro
        PROFILE_EMAIL: udoprog@spotify.com
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell

secrets:
    - SMTP_PASS
    - IMAP_PASS
    - SMTP_URL
