variables:
    PRIMARY_MAIL: personal
    SECONDARY_MAIL: work

profiles:
    home:
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell
    remote:
        PROFILE_TMUX_PREFIX: C-b
        PROFILE_ZSH_THEME: afowler
    work:
        PRIMARY_MAIL: work
        SECONDARY_MAIL: personal
        PROFILE_TMUX_PREFIX: C-a
        PROFILE_ZSH_THEME: robbyrussell

secrets:
  - GPG_KEY
  - MUTT_SIGNATURE
  - PROFILE_NAME
  - NAME
  - USER
  - EMAIL
  - SMTP_PASS
  - IMAP_PASS
  - SMTP_URL
  - WORK_EMAIL
  - WORK_SMTP_PASS
  - WORK_IMAP_PASS
  - WORK_SMTP_URL
