monitor.alsa.rules = [
  {
    matches = [
      {
	device.name = "alsa_card.usb-Creative_Technology_Ltd._VF0680_Live__Cam_Socialize_HD_1080_2011082300708-02"
      }
    ]
    actions = {
      update-props = {
      	device.disabled = true
      }
    }
  }
]
