#!/bin/bash

set -e

INCOMING=$HOME/incoming

if [[ ! -d $INCOMING ]]; then
    exit 0
fi

while read file; do
    echo "Applying: $file"
    git am $file
    rm -f $file
done < <(find $INCOMING -type f -name '*.patch' | sort)
