#!/bin/bash

export ROOT=$(dirname $(dirname $(realpath $0)))
export PATH=$ROOT/bin:$PATH
export DISTRO=$($ROOT/bin/detect-distro)
export BIN=$HOME/usr/bin
export REPO=$HOME/repo

exec make --no-print-directory -C $ROOT -f $ROOT/dotfiles.mk "$@"
