#!/bin/bash
# display the last repo syncs that have happened

set -e

CMD=repologs

if [[ -z $ROOT ]]; then
    ROOT=$(dirname $(dirname $(realpath $0)))
fi

source $ROOT/utils/repolib.sh
repolib_setup

clean=false

while getopts ":ch" opt; do
    case $opt in
        c)
            clean=true
            ;;
        h)
            echo "Usage: $CMD [-c] [filter]"
            echo "Display repository sync logs (from $LOGDIR)"
            echo " -c - clean logs that are displayed."
            echo " -h - show this help."
            exit 0
            ;;
        \?)
            echo "invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac

    shift $[ $OPTIND - 1 ]
done

filter="$@"

empty=true

while read file; do
    if [[ ! -z $filter ]]; then
        case $file in
            *$filter*) ;;
            *) continue ;;
        esac
    fi

    empty=false
    cat $file

    if $clean; then
        echo "removing: $(basename $file)"
        rm -f $file
    fi
done < <(find $LOGDIR -name '*.log')

if ! $empty && ! $clean; then
    echo "use \`$CMD -c\` to clean"
fi
