#!/bin/bash
# display the last repo syncs that have happened

CMD=repologs

clean=false

while getopts ":c" opt; do
    case $opt in
        c)
            clean=true
            ;;
        \?)
            echo "invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

if [[ -z $ROOT ]]; then
    ROOT=$(dirname $(dirname $(realpath $0)))
fi

logdir=$ROOT/reposync-log

if [[ ! -d $logdir ]]; then
    echo "Creating: $logdir"
    mkdir -p $logdir
fi

empty=true

while read file; do
    empty=false
    cat $file

    if $clean; then
        echo "removing: $(basename $file)"
        rm -f $file
    fi
done < <(find $logdir -name '*.log')

if ! $empty && ! $clean; then
    echo "use \`$CMD -c\` to clean"
fi
