context.objects = [
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = default
            node.description = "Default"
            media.class      = Audio/Sink
            object.linger    = true
            audio.position   = [ FL FR ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = music
            node.description = "Music"
            media.class      = Audio/Sink
            object.linger    = true
            audio.position   = [ FL FR ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = web
            node.description = "Web"
            media.class      = Audio/Sink
            object.linger    = true
            audio.position   = [ FL FR ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = movie
            node.description = "Movie"
            media.class      = Audio/Sink
            object.linger    = true
            audio.position   = [ FL FR ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = voip
            node.description = "VoIP"
            media.class      = Audio/Sink
            object.linger    = true
            audio.position   = [ FL FR ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = microphone
            node.description = "Microphone"
            media.class      = Audio/Source/Virtual 
            object.linger    = true
            audio.position   = [ MONO ]
            monitor.channel-volumes = false
            node.param.Props = {
                volume = 1.0
                mute   = false
            }
        }
    }
]
