context.objects = [
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = null-sink
      node.description = "Null Sink"
      device.nick = "Null Sink"
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = null-source
      node.description = "Null Source"
      device.nick = "Null Source"
      media.class = Audio/Source
      object.linger = true
      audio.position = [ MONO ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
]
