context.objects = [
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = default
      node.description = Default
      device.nick = Default
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
]
