context.objects = [
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = default
      node.description = Default
      device.nick = Default
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = music
      node.description = Music
      device.nick = Music
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = web
      node.description = Web
      device.nick = Web
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = movie
      node.description = Movie
      device.nick = Movie
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = voip
      node.description = VoIP
      device.nick = VoIP
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = communication
      node.description = Communication
      device.nick = Communication
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = sfx
      node.description = SFX
      device.nick = SFX
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = microphone
      node.description = Microphone
      device.nick = Microphone
      media.class = Audio/Source/Virtual
      object.linger = true
      audio.position = [ MONO ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = bluetooth
      node.description = Bluetooth
      device.nick = Bluetooth
      media.class = Audio/Source/Virtual
      object.linger = true
      audio.position = [ MONO ]
      monitor.channel-volumes = false
      node.param.Props = {
        volume = 1.0
        mute = false
      }
    }
  }
]
