node.rules = [
  {
    matches = [
      {
        application.name = "Firefox"
      }
    ]
    actions = {
      update-props = {
        target.object = "web"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        media.role = "Music"
      }
    ]
    actions = {
      update-props = {
        target.object = "music"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        application.name = "mpv"
      }
      {
        media.role = "Movie"
      }
    ]
    actions = {
      update-props = {
        target.object = "movie"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "Discord"
      }
      {
        application.name = "Mumble"
      }
    ]
    actions = {
      update-props = {
        target.object = "voip"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        pipewire.access.portal.app_id = "com.core447.StreamController"
      }
    ]
    actions = {
      update-props = {
        target.object = "sfx"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        media.role = "Communication"
        media.class = "Stream/Output/Audio"
      }
    ]
    actions = {
      update-props = {
        target.object = "communication"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      {
        media.role = "Communication"
        media.class = "Stream/Input/Audio"
      }
    ]
    actions = {
      update-props = {
        target.object = "bluetooth"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
]
