context.exec = [
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Sink sink_name=Default channel_map=stereo"
    }
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Source/Virtual sink_name=Microphone channel_map=stereo"
    }
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Sink sink_name=Music channel_map=stereo"
    }
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Sink sink_name=Movie channel_map=stereo"
    }
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Sink sink_name=VoIP channel_map=stereo"
    }
    {
        path = "pactl"
        args = "load-module module-null-sink media.class=Audio/Sink sink_name=Web channel_map=stereo"
    }
]
