stream.rules = [
  {
    matches = [
      { application.name = "Firefox" }
    ]
    actions = {
      update-props = {
        node.target = "web"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      { media.role = "Music" }
    ]
    actions = {
      update-props = {
        node.target = "music"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      { application.name = "mpv" }
      { media.role = "Movie" }
    ]
    actions = {
      update-props = {
        node.target = "movie"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
  {
    matches = [
      { application.process.binary = "Discord" }
      { application.name = "Mumble" }
    ]
    actions = {
      update-props = {
        node.target = "voip"
        node.dont-fallback = false
        node.linger = false
      }
    }
  }
]
